# Maven

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /tmp/cdefense
       /tmp/cdefense scan --api-key=7b4e6d37-a05e-a9b2-24a7-c661052297ac --lang=java --project-name=Java_ADO
       continueOnError: true
  displayName: 'SCA Scan'

- script: |
       /tmp/cdefense sast --api-key=7b4e6d37-a05e-a9b2-24a7-c661052297ac --lang=java --project-name=Java_ADO
  displayName: 'SAST Scan'

